version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: panaderia_postgres
    environment:
      POSTGRES_DB: panaderia_db
      POSTGRES_USER: panaderia_user
      POSTGRES_PASSWORD: panaderia_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U panaderia_user -d panaderia_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: panaderia_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://panaderia_user:panaderia_pass@postgres:5432/panaderia_db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
